name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.5.2
  - seaborn=0.12.1
  - pandas=1.5.2
  - pip=22.3.1
  - pandas-profiling=2.13.0
  - pyarrow=10.0.1
  - pip:
      - wandb==0.13.7